# Generated by Django 5.2.11 on 2026-02-11 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request')], db_index=True, max_length=50, verbose_name='notification type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push notification'), ('in_app', 'In-app notification')], max_length=10, verbose_name='channel')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10, verbose_name='status')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='If set, notification will not be sent before this time.', null=True, verbose_name='scheduled for')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='error message')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_103f8a_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_0f902a_idx'), models.Index(fields=['notification_type', 'status'], name='notificatio_notific_3d525b_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='Push service URL', verbose_name='endpoint')),
                ('p256dh_key', models.TextField(help_text='Client public encryption key', verbose_name='p256dh key')),
                ('auth_key', models.TextField(help_text='Client auth secret', verbose_name='auth key')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'push subscription',
                'verbose_name_plural': 'push subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='UnsubscribeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request')], max_length=50, verbose_name='notification type')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unsubscribe_tokens', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'unsubscribe token',
                'verbose_name_plural': 'unsubscribe tokens',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
