# Generated by Django 5.2.11 on 2026-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationqueue',
            name='notification_type',
            field=models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request'), ('event_registered', 'Event registration confirmed'), ('payment_instructions', 'Payment instructions'), ('payment_confirmed', 'Payment confirmed'), ('payment_expired', 'Payment expired'), ('registration_cancelled', 'Registration cancelled'), ('waitlist_promoted', 'Promoted from waitlist')], db_index=True, max_length=50, verbose_name='notification type'),
        ),
        migrations.AlterField(
            model_name='unsubscribetoken',
            name='notification_type',
            field=models.CharField(choices=[('news_published', 'News published'), ('event_published', 'Event published'), ('event_reminder', 'Event reminder'), ('weekend_favorites', 'Weekend favorites'), ('registration_opens', 'Registration opens'), ('photo_approved', 'Photo approved'), ('membership_expiring', 'Membership expiring'), ('partner_news', 'Partner news'), ('partner_events', 'Partner events'), ('partner_event_interest', 'Partner event interest'), ('partner_event_comment', 'Partner event comment'), ('partner_event_cancelled', 'Partner event cancelled'), ('aid_request', 'Aid request'), ('mutual_aid_request', 'Mutual aid request'), ('mutual_aid_access_request', 'Mutual aid access request'), ('event_registered', 'Event registration confirmed'), ('payment_instructions', 'Payment instructions'), ('payment_confirmed', 'Payment confirmed'), ('payment_expired', 'Payment expired'), ('registration_cancelled', 'Registration cancelled'), ('waitlist_promoted', 'Promoted from waitlist')], max_length=50, verbose_name='notification type'),
        ),
    ]
