# Generated by Django 5.2.11 on 2026-02-11 17:14

import django.db.models.deletion
import uuid
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federation', '0001_initial'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutualAidPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Introductory text displayed above the helpers map.', verbose_name='Introduction')),
                ('body', wagtail.fields.StreamField([('emergency_contact', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Name', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'label': 'Role', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Phone', 'max_length': 30}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('role', 1), ('phone', 2)]], {})}, verbose_name='Emergency contacts')),
                ('default_radius_km', models.PositiveIntegerField(default=50, help_text='Default radius for the helpers map view.', verbose_name='Default map radius (km)')),
                ('enable_federation', models.BooleanField(default=False, help_text='Allow approved partner clubs to see our helpers.', verbose_name='Enable federation')),
            ],
            options={
                'verbose_name': 'Mutual Aid Page',
                'verbose_name_plural': 'Mutual Aid Pages',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AidPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_phone_on_aid', models.BooleanField(default=False, verbose_name='Show phone number')),
                ('show_mobile_on_aid', models.BooleanField(default=False, verbose_name='Show mobile number')),
                ('show_whatsapp_on_aid', models.BooleanField(default=False, verbose_name='Show WhatsApp availability')),
                ('show_email_on_aid', models.BooleanField(default=False, verbose_name='Show email address')),
                ('show_exact_location', models.BooleanField(default=False, help_text='If disabled, only the city name is shown.', verbose_name='Show exact location')),
                ('show_photo_on_aid', models.BooleanField(default=False, verbose_name='Show profile photo')),
                ('show_bio_on_aid', models.BooleanField(default=False, verbose_name='Show bio')),
                ('show_hours_on_aid', models.BooleanField(default=False, verbose_name='Show availability hours')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aid_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aid Privacy Settings',
                'verbose_name_plural': 'Aid Privacy Settings',
            },
        ),
        migrations.CreateModel(
            name='FederatedAidAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_user_id', models.CharField(max_length=100, verbose_name='External user ID')),
                ('external_display_name', models.CharField(max_length=100, verbose_name='External display name')),
                ('contacts_unlocked', models.PositiveIntegerField(default=0, help_text='Number of helper contacts this user has unlocked.', verbose_name='Contacts unlocked')),
                ('access_level', models.CharField(choices=[('view_list', 'View helpers list only'), ('contact', 'Can contact helpers')], default='view_list', max_length=20, verbose_name='Access level')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('source_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_access_grants', to='federation.federatedclub', verbose_name='Source club')),
            ],
            options={
                'verbose_name': 'Federated Aid Access',
                'verbose_name_plural': 'Federated Aid Access Grants',
                'ordering': ['-created_at'],
                'unique_together': {('source_club', 'external_user_id')},
            },
        ),
        migrations.CreateModel(
            name='FederatedAidAccessRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='Why are you requesting access?', verbose_name='Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('federated_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='mutual_aid.federatedaidaccess', verbose_name='Federated access')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
            ],
            options={
                'verbose_name': 'Federated Aid Access Request',
                'verbose_name_plural': 'Federated Aid Access Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks_received', to=settings.AUTH_USER_MODEL, verbose_name='Helper')),
                ('federated_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_unlocks', to='mutual_aid.federatedaidaccess', verbose_name='Federated access')),
            ],
            options={
                'verbose_name': 'Contact Unlock',
                'verbose_name_plural': 'Contact Unlocks',
                'ordering': ['-unlocked_at'],
                'unique_together': {('federated_access', 'helper')},
            },
        ),
        migrations.CreateModel(
            name='AidRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requester_name', models.CharField(max_length=100, verbose_name='Requester name')),
                ('requester_phone', models.CharField(blank=True, max_length=30, verbose_name='Requester phone')),
                ('requester_email', models.EmailField(blank=True, max_length=254, verbose_name='Requester email')),
                ('issue_type', models.CharField(choices=[('breakdown', 'Breakdown'), ('flat_tire', 'Flat tire'), ('fuel', 'Out of fuel'), ('accident', 'Accident'), ('tow', 'Need towing'), ('tools', 'Need tools'), ('transport', 'Need transport'), ('accommodation', 'Need accommodation'), ('other', 'Other')], default='other', max_length=20, verbose_name='Issue type')),
                ('description', models.TextField(help_text='Describe what you need help with.', verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='Where are you? Address or coordinates.', max_length=255, verbose_name='Location')),
                ('urgency', models.CharField(choices=[('low', 'Low - can wait'), ('medium', 'Medium - within a day'), ('high', 'High - urgent'), ('emergency', 'Emergency - immediate')], default='medium', max_length=20, verbose_name='Urgency')),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20, verbose_name='Status')),
                ('is_from_federation', models.BooleanField(default=False, verbose_name='From federation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aid_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Helper')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Requester (if member)')),
                ('federation_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aid_requests', to='mutual_aid.federatedaidaccess', verbose_name='Federation access')),
            ],
            options={
                'verbose_name': 'Aid Request',
                'verbose_name_plural': 'Aid Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='mutual_aid__status_24f92f_idx'), models.Index(fields=['helper'], name='mutual_aid__helper__91bac0_idx')],
            },
        ),
    ]
