# Generated by Django 5.2.11 on 2026-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
            ],
            options={
                'verbose_name': 'Event Favorite',
                'verbose_name_plural': 'Event Favorites',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('waitlist', 'Waitlist')], default='registered', max_length=20, verbose_name='Status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Registered at')),
                ('guests', models.IntegerField(default=0, verbose_name='Number of guests')),
                ('guest_names', models.TextField(blank=True, verbose_name='Guest names')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Payment status')),
                ('email', models.CharField(blank=True, help_text='Required for guest registrations.', max_length=254, verbose_name='Email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Last name')),
                ('has_passenger', models.BooleanField(default=False, verbose_name='Has passenger')),
                ('passenger_is_member', models.BooleanField(default=False, verbose_name='Passenger is a member')),
                ('passenger_first_name', models.CharField(blank=True, max_length=150, verbose_name='Passenger first name')),
                ('passenger_last_name', models.CharField(blank=True, max_length=150, verbose_name='Passenger last name')),
                ('passenger_email', models.CharField(blank=True, max_length=254, verbose_name='Passenger email')),
                ('passenger_phone', models.CharField(blank=True, max_length=30, verbose_name='Passenger phone')),
                ('passenger_fiscal_code', models.CharField(blank=True, max_length=16, verbose_name='Passenger fiscal code')),
                ('passenger_birth_date', models.DateField(blank=True, null=True, verbose_name='Passenger birth date')),
                ('passenger_emergency_contact', models.CharField(blank=True, max_length=255, verbose_name='Passenger emergency contact')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.IntegerField(default=0, verbose_name='Days before event')),
                ('hours_before', models.IntegerField(default=0, verbose_name='Hours before event')),
                ('minutes_before', models.IntegerField(default=0, verbose_name='Minutes before event')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Discount percent')),
                ('label', models.CharField(help_text="Display label for this tier, e.g. 'Early Bird'.", max_length=100, verbose_name='Label')),
                ('is_deadline', models.BooleanField(default=False, help_text='If checked, registration closes when this tier expires.', verbose_name='Is registration deadline')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['-days_before', '-hours_before', '-minutes_before'],
            },
        ),
    ]
