# Generated by Django 5.2.11 on 2026-02-11 17:14

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('website', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventfavorite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='website.eventdetailpage', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='website.eventdetailpage', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='passenger_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Passenger (member)'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='pricingtier',
            name='event_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='website.eventdetailpage', verbose_name='Event page'),
        ),
        migrations.AlterUniqueTogether(
            name='eventfavorite',
            unique_together={('user', 'event')},
        ),
    ]
