# Generated by Django 5.2.11 on 2026-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Payment amount'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, help_text='Deadline for bank transfer payments.', null=True, verbose_name='Payment expires at'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_id',
            field=models.CharField(blank=True, help_text='External payment reference from the provider.', max_length=255, verbose_name='Payment ID'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_provider',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer'), ('free', 'Free')], default='', max_length=20, verbose_name='Payment provider'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Unique reference for bank transfers (e.g. EVT-00123-A7B3).', max_length=50, verbose_name='Payment reference'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='payment_session_id',
            field=models.CharField(blank=True, help_text='Checkout Session ID (Stripe) or Order ID (PayPal).', max_length=255, verbose_name='Payment session ID'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Payment status'),
        ),
    ]
