# Generated by Django 5.2.11 on 2026-02-12 10:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('website', '0002_alter_aboutpage_body_alter_boardpage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], default='test', help_text='Only credentials for the selected mode are used at runtime.', max_length=10, verbose_name='Payment mode')),
                ('stripe_test_enabled', models.BooleanField(default=False, verbose_name='Stripe enabled (test)')),
                ('stripe_test_public_key', models.CharField(blank=True, max_length=255, verbose_name='Stripe public key (test)')),
                ('stripe_test_secret_key', models.CharField(blank=True, max_length=255, verbose_name='Stripe secret key (test)')),
                ('stripe_test_webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Stripe webhook secret (test)')),
                ('paypal_test_enabled', models.BooleanField(default=False, verbose_name='PayPal enabled (test)')),
                ('paypal_test_client_id', models.CharField(blank=True, max_length=255, verbose_name='PayPal client ID (test)')),
                ('paypal_test_secret', models.CharField(blank=True, max_length=255, verbose_name='PayPal secret (test)')),
                ('stripe_live_enabled', models.BooleanField(default=False, verbose_name='Stripe enabled (live)')),
                ('stripe_live_public_key', models.CharField(blank=True, max_length=255, verbose_name='Stripe public key (live)')),
                ('stripe_live_secret_key', models.CharField(blank=True, max_length=255, verbose_name='Stripe secret key (live)')),
                ('stripe_live_webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Stripe webhook secret (live)')),
                ('paypal_live_enabled', models.BooleanField(default=False, verbose_name='PayPal enabled (live)')),
                ('paypal_live_client_id', models.CharField(blank=True, max_length=255, verbose_name='PayPal client ID (live)')),
                ('paypal_live_secret', models.CharField(blank=True, max_length=255, verbose_name='PayPal secret (live)')),
                ('bank_transfer_enabled', models.BooleanField(default=False, verbose_name='Bank transfer enabled')),
                ('bank_account_holder', models.CharField(blank=True, max_length=255, verbose_name='Account holder')),
                ('bank_iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bank_bic', models.CharField(blank=True, max_length=11, verbose_name='BIC / SWIFT')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bank name')),
                ('bank_transfer_instructions', wagtail.fields.RichTextField(blank=True, help_text="Additional instructions shown to the user (e.g. 'Include the reference in the description').", verbose_name='Bank transfer instructions')),
                ('bank_transfer_expiry_days', models.PositiveIntegerField(default=5, help_text='Days allowed for the user to complete the bank transfer.', verbose_name='Bank transfer expiry (days)')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'payment settings',
                'verbose_name_plural': 'payment settings',
            },
        ),
    ]
