# Generated by Django 5.2.11 on 2026-02-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_paymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetailpage',
            name='allow_guests',
            field=models.BooleanField(default=True, help_text='If checked, non-logged-in users can register via the guest form.', verbose_name='Allow guest registration'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=20, verbose_name='Difficulty level'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='meeting_point',
            field=models.CharField(blank=True, help_text='Where participants should gather before the event start.', max_length=500, verbose_name='Meeting point'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='passenger_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional cost for a passenger/companion. 0 = same as base.', max_digits=8, verbose_name='Passenger fee'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='passenger_included',
            field=models.BooleanField(default=False, help_text='If checked, passenger rides for free with the main registrant.', verbose_name='Passenger included in base fee'),
        ),
        migrations.AddField(
            model_name='eventdetailpage',
            name='passenger_member_discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Percentage discount on passenger fee for active members.', verbose_name='Passenger member discount (%)'),
        ),
    ]
