# Generated by Django 5.2.11 on 2026-02-12 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_eventdetailpage_allow_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for top-level items. Select a parent for dropdown sub-items.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.navbaritem', verbose_name='Parent item'),
        ),
    ]
