# Generated by Django 5.2.11 on 2026-02-11 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedClub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the partner club', max_length=255)),
                ('short_code', models.CharField(help_text='URL-safe identifier', max_length=20, unique=True)),
                ('base_url', models.URLField(help_text='Partner site base URL')),
                ('logo_url', models.URLField(blank=True, help_text='Optional logo URL')),
                ('api_key', models.CharField(help_text='Their public API key (given to us)', max_length=64)),
                ('our_key_for_them', models.CharField(blank=True, help_text='Our key we gave them (auto-generated)', max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('share_our_events', models.BooleanField(default=False, help_text='Share our events with this partner')),
                ('auto_import', models.BooleanField(default=True, help_text='Auto-approve imported events')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Federated Club',
                'verbose_name_plural': 'Federated Clubs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('location_address', models.CharField(blank=True, max_length=500)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lon', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Sanitized HTML')),
                ('event_status', models.CharField(choices=[('EventScheduled', 'Scheduled'), ('EventCancelled', 'Cancelled'), ('EventPostponed', 'Postponed'), ('EventMovedOnline', 'Moved Online')], default='EventScheduled', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('detail_url', models.URLField(blank=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_hidden', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_events', to='federation.federatedclub')),
            ],
            options={
                'verbose_name': 'External Event',
                'verbose_name_plural': 'External Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExternalEventComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('external_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='federation.externalevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Event Comment',
                'verbose_name_plural': 'External Event Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['external_event', 'created_at'], name='federation__externa_768195_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalEventInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_level', models.CharField(choices=[('interested', 'Interested'), ('maybe', 'Maybe'), ('going', 'Going')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='federation.externalevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'External Event Interest',
                'verbose_name_plural': 'External Event Interests',
                'indexes': [models.Index(fields=['external_event'], name='federation__externa_04da6a_idx')],
                'unique_together': {('user', 'external_event')},
            },
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['start_date'], name='federation__start_d_b7d19b_idx'),
        ),
        migrations.AddIndex(
            model_name='externalevent',
            index=models.Index(fields=['is_approved', 'is_hidden'], name='federation__is_appr_8733e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='externalevent',
            unique_together={('source_club', 'external_id')},
        ),
    ]
