# Generated by Django 5.2.11 on 2026-02-12 10:36

import django.contrib.auth.validators
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0002_add_fk_fields'),
        ('website', '0002_alter_aboutpage_body_alter_boardpage_body_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubuser',
            options={'verbose_name': 'Club User', 'verbose_name_plural': 'Club Users'},
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='aid_coordinates',
            field=models.CharField(blank=True, help_text='lat,lon format', max_length=50),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='display_name',
            field=models.CharField(blank=True, help_text='Public display name (nickname)', max_length=100),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='products',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='members', to='website.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='show_real_name_to_members',
            field=models.BooleanField(default=False, help_text='Allow active members to see your real name'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='clubuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
